- name: Deploy Apache in Docker 
  hosts: 10.77.77.6
  remote_user: vagrant
  become: yes
  tasks:
    - name: Install Docker 
      pip:
        name: docker

    - name: Run Apache 
      docker_container:
        name: apache_container
        image: httpd:2.4
        state: started
        published_ports: 80:80