- name: Развёртывание веб-сервера Apache 
  hosts: localhost
  become: yes
  gather_facts: no

  tasks:

  - name: Загрузка образа 
    docker_image:
      name: httpd
      state: present

  - name: Развёртывание контейнера
    docker_container:
      name: apache
      image: httpd
      state: started
      published_ports:
        - "80:80"

  - name: Установка git
    apt:
      name: git
      state: present

  - name: Загрузка index.html из репозитория GitHub
    git:
      repo: 'https://github.com/THEISEIZ/Astra_Test.git'
      dest: /tmp/Astra_Test

  - name: Размещение web-страницы 
    command: docker cp /tmp/Astra_Test/index.html apache:/usr/local/apache2/htdocs/index.html
