- name: Сборка Docker-контейнера
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Собрать Docker образ
    docker_image:
      name: ig_apache
      tag: latest
      path: /home/vagrant/
      force: yes
      pull: yes

  - name: Запуск Docker-контейнера
    docker_container:
      name: ig_apache
      image: ig_apache:latest
      state: started
      published_ports:
        - "80:80"
