- name: Deploy Apache container
  hosts: localhost
  become: yes
  gather_facts: no

  tasks:
  - name: Pull apache httpd image
    docker_image:
      name: httpd
      state: present

  - name: Create apache container
    docker_container:
      name: apache
      image: httpd
      state: started
      published_ports:
        - "80:80"

  - name: Install git
    apt:
      name: git
      state: present

  - name: Download index.html from GitHub
    git:
      repo: 'https://github.com/THEISEIZ/Astra_Test.git'
      dest: /tmp/Astra_Test

  - name: Copy index.html to apache container
    command: docker cp /tmp/Astra_Test/index.html apache:/usr/local/apache2/htdocs/index.html
