- name: Сборка Docker-контейнера веб-сервера Apache и запуск 
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Сборка образа Docker
    docker_image:
      name: ivangoryainov_apache
      tag: latest
      path: /home/vagrant/
      pull: yes

  - name: Запуск Docker-контейнера
    docker_container:
      name: ivangoryainov_apache
      image: ivangoryainov_apache:latest
      state: started
      published_ports:
        - "80:80"
