- name: Deploy Nginx container
  hosts: localhost
  become: yes
  gather_facts: no

  tasks:
  - name: Pull nginx image
    docker_image:
      name: nginx
      state: present

  - name: Create nginx container
    docker_container:
      name: nginx
      image: nginx
      state: started
      published_ports:
        - "8080:80"
