- name: Deploy Nginx in Docker container
  hosts: 10.77.77.6
  remote_user: vagrant
  become: yes
  tasks:
    - name: Run Nginx container
      docker_container:
        name: nginx_container
        image: nginx:latest
        state: started
        published_ports: 80:80
