- name: Развёртывание Docker контейнера с Nginx
  hosts: localhost
  become: yes
  gather_facts: no

  tasks:
  - name: Загрузка образа Nginx из репозитория Docker
    docker_image:
      name: nginx
      state: present

  - name: Развёртывание Docker контейнера
    docker_container:
      name: nginx
      image: nginx
      state: started
      restart_policy: always
      published_ports:
        - "8080:80"
